### ISSUE TITLE
Fails when rustup is not available

### ISSUE THREAD

**Issue by Nemo157** [taiki-e/cargo-minimal-versions#29]
```console
> cargo minimal-versions check
info: running `rustup run nightly cargo update -Z minimal-versions`
error: could not execute process `rustup run nightly cargo update -Z minimal-versions` (never executed): No such file or directory (os error 2)
```

My setup is complicated a bit because [my `rustc` pretends not to be nightly](https://github.com/Nemo157/dotfiles/blob/main/shells/rust/wrap-rust.nix#L22) to try and avoid buggy nightly detecting dependencies.

I guess I could setup a noöp shell script emulating `rustup run` too :upside_down_face:

**Comment by taiki-e** [comment]
Support for cases where rustup was unavailable was already implemented, but additional action was required on the user end. [v0.1.27](https://github.com/taiki-e/cargo-minimal-versions/releases/tag/v0.1.27) which improves it, should address this issue.

**Comment by taiki-e** [comment]
I think https://github.com/taiki-e/cargo-minimal-versions/commit/519ab48d78c33f2482016b09f3d555b5c188bcc4 (Refer cargo version instead of rustc version) alone would have probably been enough for your particular case. (However, a similar problem will occur again if you start manipulating the cargo's version output.)
